import * as dotenv from "dotenv";
import axios from "axios";
import { createError } from "../error.js";
import { v2 as cloudinary } from "cloudinary";

// Load environment variables
dotenv.config();

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

export const generateImage = async (req, res, next) => {
  try {
    const prompt = req.body.prompt;
    if (!prompt) {
      throw createError(400, "Prompt is required");
    }

    console.log(`Generating image for prompt: "${prompt}"`);

    // Initiate image generation with AI Horde
    const hordeResponse = await axios.post(
      "https://stablehorde.net/api/v2/generate/async",
      {
        prompt: prompt,
        params: { n: 1 },
      },
      {
        headers: {
          apikey: process.env.STABLE_HORDE_API_KEY || "0000000000",
          "Content-Type": "application/json",
        },
      }
    );

    const generationId = hordeResponse.data.id;
    console.log(`AI Horde generation initiated. ID: ${generationId}`);

    // Poll for status
    let imageUrl = null;
    let attempts = 0;
    const maxAttempts = 60; 

    while (attempts < maxAttempts) {
      // Wait 1 second
      await new Promise((resolve) => setTimeout(resolve, 1000));

      const statusResponse = await axios.get(
        `https://stablehorde.net/api/v2/generate/status/${generationId}`
      );

      if (statusResponse.data.done) {
        if (
          statusResponse.data.generations &&
          statusResponse.data.generations.length > 0
        ) {
          imageUrl = statusResponse.data.generations[0].img;
        }
        break;
      }
      attempts++;
    }

    if (!imageUrl) {
      throw createError(500, "Image generation failed or timed out.");
    }

    console.log(`Image generated by AI Horde: ${imageUrl}`);

    const imageResponse = await axios.get(imageUrl, {
      responseType: "arraybuffer",
    });

    // Convert the response to base64 format
    const imageBase64 = `data:image/png;base64,${Buffer.from(
      imageResponse.data
    ).toString("base64")}`;

    // Upload the base64 image to Cloudinary
    const uploadResponse = await cloudinary.uploader.upload(imageBase64, {
      folder: "generated_images", 
      timeout: 60000,
    });

    console.log(`Image uploaded to Cloudinary: ${uploadResponse.secure_url}`);

    // Send the uploaded image URL as a response
    return res.status(200).json({
      photo: uploadResponse.secure_url,
    });
  } catch (error) {
    console.error("Error generating image:", error);

    // Pass the error to the next middleware with an appropriate status
    next(
      createError(
        error?.response?.status || 500,
        error?.response?.data?.message || error?.message
      )
    );
  }
};
